"use strict";
var RoboGame;
(function (RoboGame) {
    let FIELDATTRIBUTE;
    (function (FIELDATTRIBUTE) {
        FIELDATTRIBUTE[FIELDATTRIBUTE["PLAINS"] = 0] = "PLAINS";
        FIELDATTRIBUTE[FIELDATTRIBUTE["ORE"] = 1] = "ORE";
        FIELDATTRIBUTE[FIELDATTRIBUTE["OIL"] = 2] = "OIL";
        FIELDATTRIBUTE[FIELDATTRIBUTE["FOREST"] = 3] = "FOREST";
        FIELDATTRIBUTE[FIELDATTRIBUTE["MOUNTAIN"] = 4] = "MOUNTAIN";
        FIELDATTRIBUTE[FIELDATTRIBUTE["WATER"] = 5] = "WATER";
        FIELDATTRIBUTE[FIELDATTRIBUTE["WRECKAGE"] = 6] = "WRECKAGE";
        FIELDATTRIBUTE[FIELDATTRIBUTE["WORLDBORDER"] = 7] = "WORLDBORDER";
        FIELDATTRIBUTE[FIELDATTRIBUTE["FACTORY"] = 8] = "FACTORY";
    })(FIELDATTRIBUTE = RoboGame.FIELDATTRIBUTE || (RoboGame.FIELDATTRIBUTE = {}));
})(RoboGame || (RoboGame = {}));
//# sourceMappingURL=FieldAttribute.js.map