"use strict";
var RoboGame;
(function (RoboGame) {
    let FIELDATTRIBUTE;
    (function (FIELDATTRIBUTE) {
        FIELDATTRIBUTE[FIELDATTRIBUTE["PLAINS"] = 0] = "PLAINS";
        FIELDATTRIBUTE[FIELDATTRIBUTE["ORE"] = 1] = "ORE";
        FIELDATTRIBUTE[FIELDATTRIBUTE["OIL"] = 2] = "OIL";
        FIELDATTRIBUTE[FIELDATTRIBUTE["FOREST"] = 3] = "FOREST";
        FIELDATTRIBUTE[FIELDATTRIBUTE["MOUNTAIN"] = 4] = "MOUNTAIN";
        FIELDATTRIBUTE[FIELDATTRIBUTE["QUEST"] = 5] = "QUEST";
        FIELDATTRIBUTE[FIELDATTRIBUTE["ENEMY"] = 6] = "ENEMY";
        FIELDATTRIBUTE[FIELDATTRIBUTE["WATER"] = 7] = "WATER";
        FIELDATTRIBUTE[FIELDATTRIBUTE["WRECKAGE"] = 8] = "WRECKAGE";
    })(FIELDATTRIBUTE = RoboGame.FIELDATTRIBUTE || (RoboGame.FIELDATTRIBUTE = {}));
    class WorldMap {
    }
    RoboGame.WorldMap = WorldMap;
})(RoboGame || (RoboGame = {}));
//# sourceMappingURL=WorldMap.js.map